FROM node:24-alpine AS builder

WORKDIR /app

# Disable Next.js Telemetry
ENV NEXT_TELEMETRY_DISABLED=1 

COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . .

ENV PORT=${PORT}
EXPOSE ${PORT}

CMD ["npm", "run", "dev"]
